version: '3.9'

volumes:
  static_volume:

services:
  nginx:
    image: nginx:latest
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
    depends_on:
      - my_app

  my_app:
    build: .
    image: app:1.2.0
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static